apiVersion: v1
kind: Pod
metadata:
  name: whoami
  labels:
    app: whoami
    version: v1
    role: backend
spec:
  containers:
  - name: whoami
    image: containous/whoami:v1.4.0
    ports:
    - containerPort: 80
      name: http
      protocol: TCP 
    # resources:
    #   requests:
    #     memory: "64Mi"
    #     cpu: "250m"
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
